services:
  cadvisor:
    image: 'gcr.io/cadvisor/cadvisor:v0.52.1'
    container_name: cadvisor
    privileged: true
    pid: host
    ports:
      - '9109:9109'
    devices:
      - /dev/kmsg
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:ro'
      - '/run:/run:ro'
      - '/sys:/sys:ro'
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    command:
      - '-port=9109'
      - '-docker_only=true'
      - '-store_container_labels=true'
    networks:
      - coolify-observability
  docker_container_exporter:
    image: oriolrius/docker_container_exporter:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8118:8118"
    networks:
      - coolify-observability
  nodeexporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
    networks:
      - coolify-observability
networks:
  coolify-observability:
    external: true