version: '3'
services:
  cadvisor:
    image: 'gcr.io/cadvisor/cadvisor:latest'
    container_name: cadvisor
    volumes:
      - '/:/rootfs:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/dev/disk/:/dev/disk:ro'
    command:
      - '-port=9109'
    ports:
      - '9109:9109'
    devices:
      - /dev/kmsg
    privileged: true
    restart: always
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--tries=1'
        - '--spider'
        - 'http://localhost:9109/healthz'
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - coolify-observability
networks:
  coolify-observability:
    external: true