services:
  cadvisor:
    image: 'gcr.io/cadvisor/cadvisor:v0.52.1'
    container_name: cadvisor
    privileged: true
    pid: host
    devices:
      - /dev/kmsg
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:ro'
      - '/run:/run:ro'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command:
    ports:
      - '9109:9109'
      - '-port=9109'
      - '-docker_only=true'
      - '-store_container_labels=true'
    networks:
      - coolify-observability
networks:
  coolify-observability:
    external: true